title: Adventures with Perl and Linux
author: Csaba Simándi
email: x1mandi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This blog is a place, where I am collecting artifacts (anything useful found or invented during work, life, practicing, etc.) I have found during 
  my adventures with the Perl programming language, Linux and other technology related topics.
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
