title: Adventures with Perl and Linux
author: Csaba Simándi
email: x1mandi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This blog is a place, where I am collecting artifacts (anything useful found or invented during work, life, practicing, etc.) I have found during 
  my adventures with the Perl programming language, Linux and other technology related topics.
  
# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"
  
# social links
  github_username:  x1mandi # DO NOT include the @ character, or else the build will fail!
  linkedin_username: csaba-simandi-17688a7a # DO NOT include the @ character, or else the build will fail!
  # devto: jekyll
  # dribbble: jekyll
  # facebook: jekyll
  # flickr:   jekyll
  # instagram: jekyll
  # linkedin: jekyll
  # pinterest: jekyll
  # youtube: jekyll
  # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
  # youtube_channel_name: CloudCannon
  # telegram: jekyll
  # googleplus: +jekyll
  # microdotblog: jekyll
  # keybase: jekyll

# Mastodon instances
  # mastodon:
  # - username: jekyll
  #   instance: example.com
  # - username: jekyll2
  #   instance: example.com

# GitLab instances
  # gitlab:
  # - username: jekyll
  #   instance: example.com
  # - username: jekyll2
  #   instance: example.com
    
# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

plugins:
 - jekyll-feed
 - jekyll-seo-tag
show_excerpts: false # set to false to remove excerpts on the homepage

theme: minima


